<Project>
  <PropertyGroup Condition="'$(PerformanceLoggingDefault)' == 'true'">
    <DefineConstants>$(DefineConstants);SMELTANDFUEL_PERFORMANCE_LOGGING_DEFAULT</DefineConstants>
  </PropertyGroup>

  <Target Name="CopyPluginToRelease" AfterTargets="Build"
          Condition="'$(Configuration)' == 'Release' and '$(ReleaseOutputPath)' != ''">
    <MakeDir Directories="$(ReleaseOutputPath)" />
    <Copy SourceFiles="$(TargetPath)"
          DestinationFolder="$(ReleaseOutputPath)" />
  </Target>
</Project>
